### ISSUE TITLE
Install necessary tooling

### ISSUE THREAD

**Issue by wgancarz** [ohio-studio/mechs-vs-minions#13]
We took a long break from Java, so we need to set everything up again.

We'll need:
- JDK 16
- IntellIJ IDEA Community
- Git

I recommend installing it all via [Chocolatey](https://chocolatey.org/install#individual):
```powershell
#install Chocolatey (command copied from Chocolatey documentation)
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

#install the tools
choco install adoptopenjdk
choco install intellijidea-community
choco install git
```

Then, clone the repository in a directory of your choice:
```powershell
git clone https://github.com/ohio-studio/mechs-vs-minions
```
_You might need to restart PowerShell after Git installation before you run `git clone`._

Then, open the project in IntelliJ, by selecting Open and choosing the **`pom.xml`** file in this repository's directory.
`pom.xml` is the main project file for all Maven projects. Selecting this file make IntelliJ import everything as a proper Maven solution.

Then, open the Main class. Try to _Run_ it.
If it won't work - which is likely - you will need to set a path to your JDK installation in IntelliJ settings.
You should see a line of console log in the output.
```text
Welcome to Mechs vs Minions.
```

Then, expand _Maven_ menu from the right-hand side of your window.
Under _Lifecycle_, select _test_.
Maven should build your application and run all the tests in there.
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

We will also need to make sure you are properly authorized to Git, so that you can push your code. We'll do this in a followup ticket, where you'll write your first Class.

**Acceptance Criteria**:
* Post the following screenshots of your IntellIJ IDEA in this ticket:
  * one where we can see the output of the main method
  * one where we can see the Maven test command results

**Comment by DamianChristopherFrancis** [comment]
hey,

thanks for babysitting me.

please find screenshot as the attachment.

![image](https://user-images.githubusercontent.com/49077887/127572113-933ccb9f-0827-4fa4-80b2-20112b30eb11.png)

Cheers

**Comment by wgancarz** [comment]
lgtm
